export const appColors = [
    { name: "Blue", class: "bg-blue-500", gradient: "bg-gradient-to-br from-blue-400 to-blue-600" },
    { name: "Purple", class: "bg-purple-500", gradient: "bg-gradient-to-br from-purple-400 to-purple-600" },
    { name: "Green", class: "bg-green-500", gradient: "bg-gradient-to-br from-green-400 to-green-600" },
    { name: "Red", class: "bg-red-500", gradient: "bg-gradient-to-br from-red-400 to-red-600" },
    { name: "Orange", class: "bg-orange-500", gradient: "bg-gradient-to-br from-orange-400 to-orange-600" },
    { name: "Yellow", class: "bg-yellow-500", gradient: "bg-gradient-to-br from-yellow-400 to-yellow-600" },
    { name: "Pink", class: "bg-pink-500", gradient: "bg-gradient-to-br from-pink-400 to-pink-600" },
    { name: "Teal", class: "bg-teal-500", gradient: "bg-gradient-to-br from-teal-400 to-teal-600" },
    { name: "Indigo", class: "bg-indigo-500", gradient: "bg-gradient-to-br from-indigo-400 to-indigo-600" },
    { name: "Cyan", class: "bg-cyan-500", gradient: "bg-gradient-to-br from-cyan-400 to-cyan-600" },
    { name: "Rose", class: "bg-rose-500", gradient: "bg-gradient-to-br from-rose-400 to-rose-600" },
    { name: "Emerald", class: "bg-emerald-500", gradient: "bg-gradient-to-br from-emerald-400 to-emerald-600" },
    { name: "Violet", class: "bg-violet-500", gradient: "bg-gradient-to-br from-violet-400 to-violet-600" },
    { name: "Amber", class: "bg-amber-500", gradient: "bg-gradient-to-br from-amber-400 to-amber-600" },
    { name: "Lime", class: "bg-lime-500", gradient: "bg-gradient-to-br from-lime-400 to-lime-600" },
    { name: "Fuchsia", class: "bg-fuchsia-500", gradient: "bg-gradient-to-br from-fuchsia-400 to-fuchsia-600" },
    { name: "Sky", class: "bg-sky-500", gradient: "bg-gradient-to-br from-sky-400 to-sky-600" },
    { name: "Slate", class: "bg-slate-500", gradient: "bg-gradient-to-br from-slate-400 to-slate-600" },
    { name: "Zinc", class: "bg-zinc-500", gradient: "bg-gradient-to-br from-zinc-400 to-zinc-600" },
    { name: "Neutral", class: "bg-neutral-500", gradient: "bg-gradient-to-br from-neutral-400 to-neutral-600" },
];
